### ISSUE TITLE
Add private key saving and recovery

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-communications-node#12]
## Flow
When starting the node for the first time the node should:

1. Generate new private key
2. Ask for encrypting the key (optional)
3. Save it in the `node-keychain` folder

Starting for second time onwards , the node should:

1. Detect there is a key and load it
2. Ask for password for the key
3. Start the node with the same id (public key)

There should also be a way to overwrite using flag like `--private-key=...` as well as `--key-password=...` that have priority and are used in the first place.

## Tasks
- [x] Saving the key
- [x] Encrypting the key
- [x] Recovery
- [x] Overwriting with `--private-key` flag
- [x] Providing password with `--key-password` flag
- [ ] Adding tests to check all this
