### ISSUE TITLE
Update libp2p

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-communications-node#13]
## Description
libp2p is undergoing big rewrite from callbacks to promises. The current code would not work with the latest version

## Tasks
- [ ] update to latest version of libp2p (can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) and then `ncu` or autopugrade with `ncu -u`)
- [ ] update the forked repos as well
- [ ] modify the code to ensure it works, rewrite everything with promisses
