### ISSUE TITLE
Fix the `@types/node-forge` for `asn1.integerToDer`

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-communications-node#46]
## Rationale
The current version of `@types/node-forge` is missing number of functions in the type definitions. This prevented us from using for example the `asn1.integerToDer` function [here](https://github.com/rsksmart/rif-communications-node/pull/42/files#diff-013d50b248ca2db8ca00ee0863fba602L48-R49).

## Tasks
- [ ] Review the https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-forge and what are the missing functions for the `asn1` interface
- [ ] Add the missing functions and definitions and propose it to the https://github.com/DefinitelyTyped project
- [ ] Get the PR to be merged and update our types definition
